### ISSUE TITLE
Именование интерфейсов

### ISSUE THREAD

**Issue by neikila** [IlyaFloppy/Park-DZ1#1]
В джаве (в андроиде во всяком случае) не принято называть интерфейсы начиная с I.
Типичный ситуация обычно выглядит следующимо образом:
NumberSelectedListener - интерфейс и 
NumberSelectedListenerImpl - реализация интерфейса.

**Comment by IlyaFloppy** [comment]
Fixed - c0d4dd0dde399caa39544692822e786c07d388b0
